DROP TABLE answers;
DROP TABLE questions;
DROP TABLE user;

CREATE TABLE user(
userID INT PRIMARY KEY AUTO_INCREMENT,
userName VARCHAR(12),
password VARCHAR(50)
)ENGINE=INNODB;

CREATE TABLE questions (
userID INT,
qstID INT PRIMARY KEY AUTO_INCREMENT,
title VARCHAR(200),
qst VARCHAR(500),
views INT,
FOREIGN KEY (userID) REFERENCES user (userID)
)ENGINE=INNODB;

CREATE TABLE answers (
userID INT,
qstID INT,
ansID INT PRIMARY KEY AUTO_INCREMENT,
ans VARCHAR(700),
votes INT,
FOREIGN KEY (qstID) REFERENCES questions (qstID),
FOREIGN KEY (userID) REFERENCES user (userID)
)ENGINE=INNODB;
